---
- name: Webserver content config
  hosts: dev
  tasks: 
    - name: change the content in webpage
      ansible.builtin.copy:
        src: index.j2
        dest: /var/www/html/index.html
      notify: 
        restart_service
  handlers:
    - name: restart_service
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: yes
      
